export const path = {
    HOME: "/",
    LOGIN: "/login",
    REGISTER: "/register",
    SYSTEM: "/system",
    DOCTOR_APPOINTMENT: "/doctor-appointment",
    HOSPITAL_APPOINTMENT: "/hospital-appointment",
    CLINIC_APPOINTMENT: "/clinic-appointment",
    TEST_APPOINTMENT: "/test-appointment",
    HCP: "/hcp",
    CLINIC: "/clinic",
    SCHEDULE: "/schdule",
    PAYMENT_HISTORY: "/payment-history",
    PROFILE: "/profile",
};
